### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [fasetto/cryptocurrency-robot#2]
Hey bro. I'm beginner.
Help me with this problem. Where I choose English - /ticker - Choose BTC/USD - Choose Market (Poloniex) - I recived message "Unsupported pair."

**Comment by juanluisbaptiste** [comment]
Probably the PR that fixes this issue won't be merged as this project seems abanadoned. I someone needs a working version you can find it [here](https://github.com/juanluisbaptiste/cryptocurrency-robot).

**Comment by fasetto** [comment]
@juanluisbaptiste Yeah, that is right. I am not working on this project anymore.  I didn't see your PR because I wasn't mentioned.
If you want to continue to develop, I can add you as collaborator.

**Comment by juanluisbaptiste** [comment]
> @juanluisbaptiste Yeah, that is right. I am not working on this project anymore. I didn't see your PR because I wasn't mentioned.
> If you want to continue to develop, I can add you as collaborator.

@fasetto after I fixed this I have found other issues that probably I will not spend my time fixing them.
